#===============================================================================
# Create S3 Bucket, Put bucket policy, Export CloudWatch Logs in this Bucket
# through lambda function and CloudWatch rule to trigger lambda everyday.
#
# (c) Enquizit, Inc 2019
# v1.0 2020-07-15
#================================================================================
AWSTemplateFormatVersion: '2010-09-09'
Description: Set retention retention period. 
###################################################
#
# CloudFormation Interface Metadata
#
###################################################
Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Cloudwatch Logs Information
      Parameters:
      - pCloudwatchLogsRetentionPeriod
      - pLambdaTiggerSchedular
      - pTargetId
      
      
    ParameterLabels:
      pCloudwatchLogsRetentionPeriod:
        default: Retention Period in Days
      pLambdaTiggerSchedular:
        default: Cron Job
      pTargetId:
        default: Targets Id for CloudWatch Rule
      
      
###################################################
#
# Template Parameter Definitions
#
###################################################
Parameters: 
    
  pCloudwatchLogsRetentionPeriod:
    Type: Number
    Default: 30
    Description: Enter retention period (in days) of Cloudwatch Logs.
    
  pLambdaTiggerSchedular:
    Type: String
    Default: cron(0 6 * * ? *)
    Description: Enter Cron Job to schedule the lambda trigger time.
    
  pTargetId:
    Type: String
    Default: "cw-lg-expt-Func"
    Description: A name for the target. Use a string that will help you identify the target. Each target associated with a rule must have an Id unique for that rule.


###################################################
#
# Template Resource Definitions
#
###################################################
  
Resources:

  # Custom lambda that Sets the cloudwatch Logs retention period
  rCWLogSetRetentionFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt rLambdaExRole.Arn
      Code: '../Lambda/cloudwatch_logs_setting_rentention_policy'
      Runtime: python3.7
      Timeout: 240
      Environment:
        Variables:
          cw_logs_retention:  !Ref pCloudwatchLogsRetentionPeriod

      
 # Lambda execution Role
  rLambdaExRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AWSCloudwatchLogsExporterPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:  
              - Effect: Allow
                Action:
                  # - 'logs:*'
                  - 'logs:DescribeLogGroups'
                  - 'logs:PutRetentionPolicy'
                Resource: '*'
 

  # cloudwatch Rule to trigger the lambda function    
  rScheduledRuleForLambdaFunc: 
    Type: AWS::Events::Rule
    DependsOn: rCWLogSetRetentionFunction
    Properties: 
      Description: "Scheduled Rule for export cloudwatch logs to s3 Bucket"
      ScheduleExpression: !Ref pLambdaTiggerSchedular
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt rCWLogSetRetentionFunction.Arn
          Id: 
            Ref: pTargetId
            
            
            
  # Permission for events to invoke lambda function       
  rPermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    DependsOn: rCWLogSetRetentionFunction
    Properties: 
      FunctionName: !Ref rCWLogSetRetentionFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt rScheduledRuleForLambdaFunc.Arn


