#==================================================#==================================================
# This CloudFormation template will create AWS S3 bucket to store packed Lambda function.
# Moreover, it gives permission  to access the packaged lambda function for different account
# while deploying as stackset.
#Note that: This bucket name must be used while packaging lambda using CLI
#==================================================#==================================================
 
AWSTemplateFormatVersion: 2010-09-09
Description: Create AWS S3 bucket for Lambda 

###################################################
#
# Template Parameter Definitions
#
###################################################
Parameters:
  BucketNameForLambda:
    Type: String
    Description: ARN of CMK used for encypting the Source bucket
    Default: ''
  ARNlist:
    Type: CommaDelimitedList
    Description: ARNs for the root account to deply.
    Default: arn:aws:iam::[acctnumber]:root,arn:aws:iam::[acctnumber]:root
    
    
###################################################
#
# Template Resource Definitions
#
###################################################
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameForLambda
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref BucketNameForLambda
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowGetObjetOnly
            Effect: Allow
            Principal:
              AWS:  !Ref ARNlist
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub '${Bucket.Arn}/*'
            
            
            
###################################################
#
# Template Output Definitions
#
###################################################
           
Outputs:
  S3BucketName:
    Description: The  Bucket Name
    Value: !Ref Bucket 
