#===============================================================================
# Create a Resource Data Sync for Systems Manager to get inventory information.
# scenario, this template must be run in Data Sender account(Shared Account or through stack set in Master or central account).
#
# (c) Enquizit, Inc 2019
# v1.0 2020-07-15
#================================================================================
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Resource Data Sync. 
###################################################
#
# CloudFormation Interface Metadata
#
###################################################
Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: ResourceDataSync Information
      Parameters:
      - pResourceDataSyncBucketName
      - pSyncName
      - pSyncType
      - pBucketPrefix
      - pBucketRegion
      
    ParameterLabels:
      pResourceDataSyncBucketName:
        default: Event ResourceDataSyncBucket Name
      pSyncName:
        default: Sync Name
      pSyncType:
        default: Sync Type
      pBucketRegion:
        default: Bucket Region
      pBucketPrefix:
        default:  Bucket Prefix(folder name)
      
###################################################
#
# Template Parameter Definitions
#
###################################################
Parameters: 
    
  pResourceDataSyncBucketName:
    Type: String
    Default: resourcedatasync
    Description: Enter Name of Resource Data Sync Bucket(Lower Case).
  
  pSyncName:
    Type: String
    Default: data-sync
    Description: Enter Sync Name.
    
  pSyncType:
    Type: String
    Default: SyncToDestination
    Description: Enter Sync Type SyncFromSource(from AWS Organizations or from multiple AWS Regions), SyncToDestination(data to an S3 bucket) is Default.

  pBucketRegion:
    Type: String
    Default: us-east-1
    Description: Enter Bucket Region, us-east-1 is Default.

  pBucketPrefix:
    Type: String
    Default: shared-account
    Description: Enter Bucket Prefix(folder name), shared-account is Default.
    
###################################################
#
# Resource definitions
#
###################################################

Resources:

  rBasicResourceDataSync:
    Type: AWS::SSM::ResourceDataSync
    Properties:
      SyncName: !Ref pSyncName
      SyncType: !Ref pSyncType
      S3Destination:
        BucketName: !Ref pResourceDataSyncBucketName
        BucketRegion: !Ref pBucketRegion
        SyncFormat: JsonSerDe
        BucketPrefix: !Ref pBucketPrefix
        # KMSKeyArn: kmsKeyARN
